/**
 * app_config.h
 *
 * Central configuration for the STM32L562 + FreeRTOS wireless bridge
 * application (PC config UART, EEPROM, ESP32-C3-WROOM AT link, Cyclone IV
 * measurement link).
 *
 * NOTE: This file only declares the peripheral handles / pins the
 * application expects. The actual MX_USARTx_Init(), MX_I2C1_Init(),
 * MX_GPIO_Init() etc. must be generated by STM32CubeMX for your board
 * revision and assigned to the extern handles below (normally done in
 * main.c). Adjust pin/peripheral assignments here to match your schematic.
 */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "stm32l5xx_hal.h"
#include "cmsis_os2.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------------ *
 * Peripheral handle bindings
 *
 *  USART1 - PC configuration link      (PA9 = TX, PA10 = RX)   115200 8N1
 *  USART2 - ESP32-C3-WROOM AT link     (PA2 = TX, PA3  = RX)   115200 8N1
 *  USART3 - Cyclone IV measurement link(PB10 = TX, PB11 = RX)  921600 8N1
 *  I2C1   - EEPROM (24LC256 class)     (PB6 = SCL, PB7 = SDA)
 *  EXTI   - Cyclone IV "trigger" pin   (PB0, falling edge, pull-up)
 * ------------------------------------------------------------------------ */
extern UART_HandleTypeDef huart1;      /* PC config link            */
extern UART_HandleTypeDef huart2;      /* ESP32-C3-WROOM AT link    */
extern UART_HandleTypeDef huart3;      /* Cyclone IV data link      */
extern I2C_HandleTypeDef  hi2c1;       /* EEPROM                    */
extern DMA_HandleTypeDef  hdma_usart3_rx;

#define PC_UART_HANDLE          (&huart1)
#define ESP32_UART_HANDLE       (&huart2)
#define FPGA_UART_HANDLE        (&huart3)
#define EEPROM_I2C_HANDLE       (&hi2c1)

#define FPGA_TRIGGER_GPIO_PORT  GPIOB
#define FPGA_TRIGGER_GPIO_PIN   GPIO_PIN_0

/* ------------------------------------------------------------------------ *
 * EEPROM (24LC256-class I2C EEPROM)
 * ------------------------------------------------------------------------ */
#define EEPROM_I2C_ADDR_7BIT     (0x50U)
#define EEPROM_I2C_ADDR_HAL      (EEPROM_I2C_ADDR_7BIT << 1)
#define EEPROM_PAGE_SIZE_BYTES   (64U)
#define EEPROM_CONFIG_BASE_ADDR  (0x0000U)
#define EEPROM_I2C_TIMEOUT_MS    (100U)

/* ------------------------------------------------------------------------ *
 * Buffer sizes / protocol limits
 * ------------------------------------------------------------------------ */
#define WIFI_SSID_MAX_LEN        (32U)
#define WIFI_PASS_MAX_LEN        (64U)
#define IP_STR_MAX_LEN           (16U)   /* "255.255.255.255\0" */

#define PC_UART_RX_RINGBUF_SIZE  (256U)
#define PC_UART_LINE_MAX_LEN     (128U)

#define ESP32_UART_RX_RINGBUF_SIZE (512U)
#define ESP32_AT_LINE_MAX_LEN      (256U)
#define ESP32_DEFAULT_AT_TIMEOUT_MS (2000U)
#define ESP32_WIFI_JOIN_TIMEOUT_MS  (15000U)
#define ESP32_TCP_CONNECT_TIMEOUT_MS (10000U)
#define ESP32_SEND_TIMEOUT_MS       (5000U)

#define FPGA_FRAME_MAX_LEN       (1024U)  /* max Cyclone IV payload bytes */
#define FPGA_RX_IDLE_TIMEOUT_MS  (200U)
#define FPGA_RX_TOTAL_TIMEOUT_MS (1000U)  /* max wait for a full frame after trigger */

/* ------------------------------------------------------------------------ *
 * FreeRTOS task priorities / stack sizes (in words)
 * ------------------------------------------------------------------------ */
#define TASK_PRIO_PC_UART   (osPriorityNormal)
#define TASK_PRIO_ESP32     (osPriorityAboveNormal)
#define TASK_PRIO_FPGA_IF   (osPriorityAboveNormal1)

#define TASK_STACK_PC_UART  (384U)
#define TASK_STACK_ESP32    (512U)
#define TASK_STACK_FPGA_IF  (384U)

#ifdef __cplusplus
}
#endif

#endif /* APP_CONFIG_H */
