/**
 * app_config.h
 *
 * Central configuration for the STM32L562 + FreeRTOS wireless bridge
 * application (PC config UART, EEPROM, ESP32-C3-WROOM AT link, Cyclone IV
 * measurement link).
 *
 * NOTE: This file only declares the peripheral handles / pins the
 * application expects. The actual MX_USARTx_Init(), MX_SPI1_Init(),
 * MX_GPIO_Init() etc. must be generated by STM32CubeMX for your board
 * revision and assigned to the extern handles below (normally done in
 * main.c). Adjust pin/peripheral assignments here to match your schematic.
 */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "stm32l5xx_hal.h"
#include "cmsis_os2.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------------ *
 * Peripheral handle bindings
 *
 *  USART1 - PC configuration link      (PA9 = TX, PA10 = RX)   115200 8N1
 *  USART2 - ESP32-C3-WROOM AT link     (PA2 = TX, PA3  = RX)   115200 8N1
 *  USART3 - Cyclone IV measurement link(PB10 = TX, PB11 = RX)  921600 8N1
 *  SPI1   - EEPROM: Winbond W25Q40CL   (PA5=SCK, PA6=MISO, PA7=MOSI, PA4=CS/GPIO)
 *  EXTI   - Cyclone IV "trigger" pin   (PB0, falling edge, pull-up)
 * ------------------------------------------------------------------------ */
extern UART_HandleTypeDef huart1;      /* PC config link            */
extern UART_HandleTypeDef huart2;      /* ESP32-C3-WROOM AT link    */
extern UART_HandleTypeDef huart3;      /* Cyclone IV data link      */
extern SPI_HandleTypeDef  hspi1;       /* W25Q40CL SPI flash        */
extern DMA_HandleTypeDef  hdma_usart3_rx;

#define PC_UART_HANDLE          (&huart1)
#define ESP32_UART_HANDLE       (&huart2)
#define FPGA_UART_HANDLE        (&huart3)
#define EEPROM_SPI_HANDLE       (&hspi1)

#define EEPROM_CS_GPIO_PORT     GPIOA
#define EEPROM_CS_GPIO_PIN      GPIO_PIN_4

#define FPGA_TRIGGER_GPIO_PORT  GPIOB
#define FPGA_TRIGGER_GPIO_PIN   GPIO_PIN_0

/* ------------------------------------------------------------------------ *
 * EEPROM: Winbond W25Q40CL (4 Mbit SPI NOR flash)
 *  - 512 KB total, 4 KB erase sectors, 256 B program pages
 *  - Page Program only clears bits (1->0); a sector MUST be erased
 *    (all bits set to 1) before it is programmed again.
 * ------------------------------------------------------------------------ */
#define EEPROM_SECTOR_SIZE_BYTES   (4096U)
#define EEPROM_PAGE_SIZE_BYTES     (256U)
#define EEPROM_CONFIG_BASE_ADDR    (0x000000UL)  /* sector 0 */
#define EEPROM_SPI_TIMEOUT_MS      (100U)
#define EEPROM_ERASE_TIMEOUT_MS    (500U)   /* W25Q40CL sector erase: typ 45ms / max 400ms */
#define EEPROM_PROGRAM_TIMEOUT_MS  (100U)   /* W25Q40CL page program: typ 0.4ms/byte / max 3ms */

/* W25Q40CL SPI NOR flash command opcodes */
#define W25Q_CMD_WRITE_ENABLE     (0x06U)
#define W25Q_CMD_READ_STATUS1     (0x05U)
#define W25Q_CMD_READ_DATA        (0x03U)
#define W25Q_CMD_PAGE_PROGRAM     (0x02U)
#define W25Q_CMD_SECTOR_ERASE     (0x20U)
#define W25Q_CMD_JEDEC_ID         (0x9FU)
#define W25Q_STATUS1_BUSY_MASK    (0x01U)

/* ------------------------------------------------------------------------ *
 * Buffer sizes / protocol limits
 * ------------------------------------------------------------------------ */
#define WIFI_SSID_MAX_LEN        (32U)
#define WIFI_PASS_MAX_LEN        (64U)
#define IP_STR_MAX_LEN           (16U)   /* "255.255.255.255\0" */

#define PC_UART_RX_RINGBUF_SIZE  (256U)
#define PC_UART_LINE_MAX_LEN     (128U)

#define ESP32_UART_RX_RINGBUF_SIZE (512U)
#define ESP32_AT_LINE_MAX_LEN      (256U)
#define ESP32_MAC_STR_LEN           (18U)   /* "xx:xx:xx:xx:xx:xx\0" */
#define ESP32_DEFAULT_AT_TIMEOUT_MS (2000U)
#define ESP32_WIFI_JOIN_TIMEOUT_MS  (15000U)
#define ESP32_TCP_CONNECT_TIMEOUT_MS (10000U)
#define ESP32_SEND_TIMEOUT_MS       (5000U)
/* upper bound for App_Esp32_ConnectAndWait(): join + tcp-connect + margin */
#define ESP32_CONNECT_WAIT_TIMEOUT_MS \
    (ESP32_WIFI_JOIN_TIMEOUT_MS + ESP32_TCP_CONNECT_TIMEOUT_MS + 3000U)

#define FPGA_FRAME_MAX_LEN       (1024U)  /* max Cyclone IV payload bytes */
#define FPGA_RX_IDLE_TIMEOUT_MS  (200U)
#define FPGA_RX_TOTAL_TIMEOUT_MS (1000U)  /* max wait for a full data frame after a trigger */
#define FPGA_CMD_START_MEASURE   (0x01U)  /* STM32 -> Cyclone IV: "start free-running measurement"
                                            * opcode, sent once per connection session (placeholder -
                                            * adjust to your FPGA's actual command) */
/* Cyclone IV free-runs on its own period after FPGA_CMD_START_MEASURE and
 * paces the trigger itself; this is just how often the loop wakes up to
 * re-check the Wi-Fi/server link while idle, not a per-cycle deadline. */
#define FPGA_TRIGGER_WAIT_TIMEOUT_MS  (30000U)
#define FPGA_RECONNECT_RETRY_DELAY_MS (2000U) /* pause between Wi-Fi reconnect attempts */

/* ------------------------------------------------------------------------ *
 * FreeRTOS task priorities / stack sizes (in words)
 * ------------------------------------------------------------------------ */
#define TASK_PRIO_PC_UART   (osPriorityNormal)
#define TASK_PRIO_ESP32     (osPriorityAboveNormal)
#define TASK_PRIO_FPGA_IF   (osPriorityAboveNormal1)

#define TASK_STACK_PC_UART  (384U)
#define TASK_STACK_ESP32    (512U)
#define TASK_STACK_FPGA_IF  (384U)

#ifdef __cplusplus
}
#endif

#endif /* APP_CONFIG_H */
