/**
  ******************************************************************************
  * @file    lan8770_stm32_port.c
  * @brief   STM32H7 HAL glue for the LAN8770 driver skeleton. See the header
  *          for assumptions about what CubeMX is expected to have set up
  *          already (ETH_HandleTypeDef heth, RMII GPIO/clocks).
  ******************************************************************************
  */

#include "lan8770_stm32_port.h"

/**
  * @brief  No extra bring-up needed here: HAL_ETH_Init() (called from
  *         MX_ETH_Init(), generated by CubeMX) already brings up the MAC's
  *         MDIO controller. This hook exists only to satisfy the
  *         lan8770_IOCtx_t.Init function-pointer contract.
  */
int32_t LAN8770_PortInit(void)
{
  return 0;
}

int32_t LAN8770_PortDeInit(void)
{
  return 0;
}

/**
  * @brief  Read one PHY (Clause 22) register over SMI/MDIO via the STM32H7
  *         Ethernet MAC's management interface.
  */
int32_t LAN8770_PortReadReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t *pRegVal)
{
  if (HAL_ETH_ReadPHYRegister(&heth, DevAddr, RegAddr, pRegVal) != HAL_OK)
  {
    return -1;
  }
  return 0;
}

/**
  * @brief  Write one PHY (Clause 22) register over SMI/MDIO.
  */
int32_t LAN8770_PortWriteReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t RegVal)
{
  if (HAL_ETH_WritePHYRegister(&heth, DevAddr, RegAddr, RegVal) != HAL_OK)
  {
    return -1;
  }
  return 0;
}

int32_t LAN8770_PortGetTick(void)
{
  return (int32_t)HAL_GetTick();
}
