<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Stm32WifiConfigTool</RootNamespace>
    <AssemblyName>Stm32WifiConfigTool</AssemblyName>
  </PropertyGroup>

</Project>
