/**
 ******************************************************************************
 * @file    main_app.c
 * @brief   Main Application - FreeRTOS Task Implementations
 ******************************************************************************
 *
 * 시스템 구조:
 *
 *  [PC UART] ←→ [UartCmdTask] → [UartCmdQueue] → [VoltageCtrlTask]
 *                                                        ↓
 *  [MCP3465R] ← [AdcReadTask] → [AdcDataQueue] → [VoltageCtrlTask]
 *       ↑ SPI                           ↓              ↓ DAC/PWM
 *                              [CommTxQueue] → [CommTxTask] → [UART + FDCAN]
 *
 *  [Internal ADC] → [FaultDetectTask] → [FaultEventQueue] → [CommTxTask]
 *                          ↓
 *                   채널 차단 (단락 시)
 *
 ******************************************************************************
 */
#include "main.h"
#include "cmsis_os2.h"
#include "app_config.h"
#include "app_types.h"
#include "app_freertos.h"
#include "mcp3465r.h"
#include "voltage_output.h"
#include "voltage_ctrl.h"
#include "uart_protocol.h"
#include "fdcan_comm.h"
#include "fault_detect.h"
#include <string.h>
#include <stdio.h>

/* ══════════════════════════════════════════════════════════════════════════
 *  External HAL Handles (generated by CubeMX in main.c)
 * ══════════════════════════════════════════════════════════════════════════ */
extern UART_HandleTypeDef   huart1;
extern SPI_HandleTypeDef    hspi1;
extern DAC_HandleTypeDef    hdac1;
extern TIM_HandleTypeDef    htim2;
extern TIM_HandleTypeDef    htim3;
extern ADC_HandleTypeDef    hadc1;
extern FDCAN_HandleTypeDef  hfdcan1;

/* ══════════════════════════════════════════════════════════════════════════
 *  Module Handles
 * ══════════════════════════════════════════════════════════════════════════ */
static MCP3465R_Handle_t        g_ext_adc;
static VoltageOutput_Handle_t   g_vout;
static UartProtocol_Handle_t    g_uart_proto;
static FdcanComm_Handle_t       g_fdcan;
static FaultState_t             g_fault_states[NUM_CHANNELS];

/* Internal ADC DMA buffer for current sensing (4 channels) */
static uint16_t g_adc_dma_buf[NUM_CHANNELS];

/* ══════════════════════════════════════════════════════════════════════════
 *  Application Initialization (call from main() before osKernelStart)
 * ══════════════════════════════════════════════════════════════════════════ */

void App_Init(void)
{
    /* ── Initialize External ADC (MCP3465R) ──────────────────────────── */
    g_ext_adc.hspi = &hspi1;
    g_ext_adc.cs_port = GPIOB;          /* PB0 = CS */
    g_ext_adc.cs_pin = GPIO_PIN_0;
    g_ext_adc.vref_mv = VREF_MV;
    MCP3465R_Init(&g_ext_adc);

    /* ── Initialize Voltage Output ────────────────────────────────────── */
    g_vout.hdac = &hdac1;
    g_vout.htim_ch2 = &htim2;
    g_vout.htim_ch3 = &htim3;
    g_vout.vref_mv = VREF_MV;
    VoltageOutput_Init(&g_vout);

    /* ── Initialize UART Protocol ─────────────────────────────────────── */
    g_uart_proto.huart = &huart1;
    UartProtocol_Init(&g_uart_proto);

    /* ── Initialize FDCAN ─────────────────────────────────────────────── */
    g_fdcan.hfdcan = &hfdcan1;
    FdcanComm_Init(&g_fdcan);

    /* ── Initialize Fault Detection ───────────────────────────────────── */
    FaultDetect_Init(g_fault_states);

    /* ── Initialize Channel Controllers ───────────────────────────────── */
    for (uint8_t i = 0; i < NUM_CHANNELS; i++) {
        VoltageCtrl_InitChannel(&g_channels[i], PI_KP, PI_KI);
    }

    /* ── Start Internal ADC with DMA (current measurement) ───────────── */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t *)g_adc_dma_buf, NUM_CHANNELS);
}

/* ══════════════════════════════════════════════════════════════════════════
 *  TASK 1: UART Command Task (Priority: High)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * - PC에서 UART로 수신한 명령을 파싱
 * - 파싱된 명령을 UartCmdQueue를 통해 VoltageCtrlTask로 전달
 * - 즉시 응답이 필요한 조회 명령은 직접 응답 전송
 *
 * ══════════════════════════════════════════════════════════════════════════ */

void StartUartCmdTask(void *argument)
{
    (void)argument;
    UartCmd_t cmd;
    uint8_t err;

    for (;;) {
        /* Wait for UART RX semaphore (released by UART RX callback) */
        if (osSemaphoreAcquire(uartRxSemHandle, osWaitForever) == osOK) {

            /* Parse received command */
            err = UartProtocol_Parse(&g_uart_proto, &cmd);

            if (err != UART_ERR_NONE) {
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendError(&g_uart_proto, err);
                osMutexRelease(uartTxMutexHandle);
                continue;
            }

            switch (cmd.cmd) {
            case CMD_SET_VOLTAGE:
            case CMD_ENABLE_CH:
            case CMD_DISABLE_CH:
            case CMD_SET_PID:
                /* Forward to VoltageCtrlTask via queue */
                osMessageQueuePut(uartCmdQueueHandle, &cmd, 0, 10);
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendOK(&g_uart_proto, "CMD_QUEUED");
                osMutexRelease(uartTxMutexHandle);
                break;

            case CMD_GET_VOLTAGE:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendVoltageData(&g_uart_proto,
                    cmd.channel,
                    g_channels[cmd.channel].target_mv,
                    g_channels[cmd.channel].measured_mv);
                osMutexRelease(uartTxMutexHandle);
                break;

            case CMD_GET_ALL:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendAllStatus(&g_uart_proto, g_channels);
                osMutexRelease(uartTxMutexHandle);
                break;

            case CMD_GET_CURRENT:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendCurrentData(&g_uart_proto,
                    cmd.channel,
                    g_channels[cmd.channel].current_ma);
                osMutexRelease(uartTxMutexHandle);
                break;

            case CMD_GET_FAULT:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    UartProtocol_SendFaultData(&g_uart_proto,
                        ch, g_fault_states[ch].current_fault);
                }
                osMutexRelease(uartTxMutexHandle);
                break;

            case CMD_SYSTEM_STATUS:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendAllStatus(&g_uart_proto, g_channels);
                osMutexRelease(uartTxMutexHandle);
                break;

            default:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                UartProtocol_SendError(&g_uart_proto, UART_ERR_INVALID_CMD);
                osMutexRelease(uartTxMutexHandle);
                break;
            }
        }
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  TASK 2: Voltage Control Task (Priority: Above Normal)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * - UartCmdQueue에서 명령 수신하여 목표 전압 설정
 * - AdcDataQueue에서 측정 데이터 수신
 * - PI 제어 루프 실행: 목표값 ↔ 측정값 차이 보정
 * - DAC/PWM 출력 갱신
 * - 주기: 10ms (100Hz)
 *
 * ══════════════════════════════════════════════════════════════════════════ */

void StartVoltageCtrlTask(void *argument)
{
    (void)argument;
    UartCmd_t cmd;
    AdcData_t adc_data;
    CommMsg_t comm_msg;
    uint32_t last_ctrl_tick = 0;

    for (;;) {
        /* ── Check for new commands (non-blocking) ────────────────────── */
        while (osMessageQueueGet(uartCmdQueueHandle, &cmd, NULL, 0) == osOK) {
            switch (cmd.cmd) {
            case CMD_SET_VOLTAGE:
                VoltageCtrl_SetTarget(&g_channels[cmd.channel], cmd.value);
                if (!g_channels[cmd.channel].enabled) {
                    g_channels[cmd.channel].enabled = true;
                    g_channels[cmd.channel].state = CH_STATE_ENABLED;
                }
                break;

            case CMD_ENABLE_CH:
                g_channels[cmd.channel].enabled = true;
                g_channels[cmd.channel].state = CH_STATE_ENABLED;
                /* Clear any fault state on re-enable */
                FaultDetect_ClearFault(&g_fault_states[cmd.channel]);
                break;

            case CMD_DISABLE_CH:
                g_channels[cmd.channel].enabled = false;
                g_channels[cmd.channel].state = CH_STATE_DISABLED;
                VoltageCtrl_Reset(&g_channels[cmd.channel]);
                /* Set output to 0 */
                osMutexAcquire(dacMutexHandle, osWaitForever);
                VoltageOutput_Disable(&g_vout, cmd.channel);
                osMutexRelease(dacMutexHandle);
                break;

            case CMD_SET_PID:
                for (uint8_t i = 0; i < NUM_CHANNELS; i++) {
                    VoltageCtrl_SetGains(&g_channels[i], cmd.param1, cmd.param2);
                }
                break;

            default:
                break;
            }
        }

        /* ── Get latest ADC data (non-blocking) ──────────────────────── */
        while (osMessageQueueGet(adcDataQueueHandle, &adc_data, NULL, 0) == osOK) {
            for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                g_channels[ch].measured_mv = adc_data.voltage_mv[ch];
            }
        }

        /* ── PI Control Loop (every CTRL_LOOP_PERIOD_MS) ─────────────── */
        uint32_t now = osKernelGetTickCount();
        if ((now - last_ctrl_tick) >= CTRL_LOOP_PERIOD_MS) {
            last_ctrl_tick = now;

            for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                if (!g_channels[ch].enabled) continue;

                /* Skip control if channel is in short-circuit fault */
                if (g_channels[ch].state == CH_STATE_FAULT_SHORT) {
                    osMutexAcquire(dacMutexHandle, osWaitForever);
                    VoltageOutput_SetRaw(&g_vout, ch, 0);
                    osMutexRelease(dacMutexHandle);
                    continue;
                }

                /* Run PI controller */
                uint16_t new_raw = VoltageCtrl_Update(&g_channels[ch],
                                                       g_channels[ch].measured_mv);

                /* Apply to output */
                osMutexAcquire(dacMutexHandle, osWaitForever);
                VoltageOutput_SetRaw(&g_vout, ch, new_raw);
                osMutexRelease(dacMutexHandle);
            }

            /* ── Send periodic status to CommTxTask ──────────────────── */
            static uint8_t report_div = 0;
            report_div++;
            if (report_div >= (COMM_TX_PERIOD_MS / CTRL_LOOP_PERIOD_MS)) {
                report_div = 0;
                memset(&comm_msg, 0, sizeof(comm_msg));
                comm_msg.type = MSG_VOLTAGE_REPORT;
                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    comm_msg.target_mv[ch] = g_channels[ch].target_mv;
                    comm_msg.measured_mv[ch] = g_channels[ch].measured_mv;
                    comm_msg.current_ma[ch] = g_channels[ch].current_ma;
                    comm_msg.state[ch] = g_channels[ch].state;
                }
                osMessageQueuePut(commTxQueueHandle, &comm_msg, 0, 0);
            }
        }

        /* Yield to lower priority tasks */
        osDelay(1);
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  TASK 3: ADC Read Task (Priority: Normal)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * - MCP3465R에서 4채널 전압을 SPI로 읽기
 * - 뮤텍스로 SPI 버스 보호
 * - 읽은 데이터를 AdcDataQueue로 전송
 * - 주기: 10ms (100Hz)
 *
 * ══════════════════════════════════════════════════════════════════════════ */

void StartAdcReadTask(void *argument)
{
    (void)argument;
    AdcData_t adc_data;

    /* Wait for system to stabilize */
    osDelay(100);

    for (;;) {
        /* Acquire SPI mutex before accessing MCP3465R */
        if (osMutexAcquire(spiMutexHandle, osWaitForever) == osOK) {

            /* Read all 4 channels from external ADC */
            HAL_StatusTypeDef status = MCP3465R_ReadAllChannels(
                &g_ext_adc, adc_data.voltage_mv);

            osMutexRelease(spiMutexHandle);

            if (status == HAL_OK) {
                adc_data.timestamp = osKernelGetTickCount();

                /* Send to VoltageCtrlTask via queue */
                osMessageQueuePut(adcDataQueueHandle, &adc_data, 0, 0);
            }
        }

        osDelay(ADC_READ_PERIOD_MS);
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  TASK 4: Fault Detection Task (Priority: Normal)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * - 내부 ADC (DMA)로 부하 전류 측정
 * - 전류값으로 단락(short) / 단선(open) 판단
 * - 디바운싱 (연속 N회 이상 감지 시 확정)
 * - 단락 시 해당 채널 출력 즉시 차단
 * - 결함 이벤트를 FaultEventQueue로 전달
 * - 주기: 50ms (20Hz)
 *
 * ══════════════════════════════════════════════════════════════════════════ */

void StartFaultDetectTask(void *argument)
{
    (void)argument;
    FaultEvent_t fault_evt;
    uint16_t current_ma[NUM_CHANNELS];

    /* Wait for system to stabilize */
    osDelay(200);

    for (;;) {
        /* ── Read current from internal ADC DMA buffer ────────────────── */
        for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
            current_ma[ch] = FaultDetect_AdcToCurrent(g_adc_dma_buf[ch]);
            g_channels[ch].current_ma = current_ma[ch];
        }

        /* ── Check each channel for faults ────────────────────────────── */
        for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
            memset(&fault_evt, 0, sizeof(fault_evt));
            fault_evt.channel = ch;
            fault_evt.timestamp = osKernelGetTickCount();

            bool new_fault = FaultDetect_Check(
                &g_fault_states[ch],
                &g_channels[ch],
                current_ma[ch],
                &fault_evt);

            if (new_fault) {
                /* Update channel state */
                if (fault_evt.fault == FAULT_SHORT_CIRCUIT) {
                    g_channels[ch].state = CH_STATE_FAULT_SHORT;

                    /* Immediately shut down output for short circuit */
                    osMutexAcquire(dacMutexHandle, osWaitForever);
                    VoltageOutput_Disable(&g_vout, ch);
                    osMutexRelease(dacMutexHandle);
                }
                else if (fault_evt.fault == FAULT_OPEN_CIRCUIT) {
                    g_channels[ch].state = CH_STATE_FAULT_OPEN;
                }

                /* Send fault event to CommTxTask */
                osMessageQueuePut(faultEventQueueHandle, &fault_evt, 0, 0);

                /* Toggle fault LED */
                HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET);
            }
        }

        /* Clear fault LED if no active faults */
        if (!FaultDetect_AnyFault(g_fault_states)) {
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET);
        }

        osDelay(FAULT_CHECK_PERIOD_MS);
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  TASK 5: Communication TX Task (Priority: Below Normal)
 * ══════════════════════════════════════════════════════════════════════════
 *
 * - CommTxQueue에서 메시지 수신
 * - UART와 FDCAN 양쪽으로 데이터 전송
 * - 주기적 전압/전류 리포트 전송
 * - 결함 이벤트 즉시 전송
 *
 * ══════════════════════════════════════════════════════════════════════════ */

void StartCommTxTask(void *argument)
{
    (void)argument;
    CommMsg_t comm_msg;
    FaultEvent_t fault_evt;

    for (;;) {
        /* ── Check for voltage/status reports ─────────────────────────── */
        if (osMessageQueueGet(commTxQueueHandle, &comm_msg, NULL, 10) == osOK) {
            switch (comm_msg.type) {
            case MSG_VOLTAGE_REPORT:
                /* Send via UART */
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    UartProtocol_SendVoltageData(&g_uart_proto,
                        ch,
                        comm_msg.target_mv[ch],
                        comm_msg.measured_mv[ch]);
                }
                osMutexRelease(uartTxMutexHandle);

                /* Send via FDCAN */
                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    FdcanComm_SendVoltageData(&g_fdcan, ch,
                        comm_msg.target_mv[ch],
                        comm_msg.measured_mv[ch],
                        g_channels[ch].dac_raw,
                        comm_msg.state[ch]);
                }
                break;

            case MSG_CURRENT_REPORT:
                osMutexAcquire(uartTxMutexHandle, osWaitForever);
                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    UartProtocol_SendCurrentData(&g_uart_proto,
                        ch, comm_msg.current_ma[ch]);
                }
                osMutexRelease(uartTxMutexHandle);

                for (uint8_t ch = 0; ch < NUM_CHANNELS; ch++) {
                    FdcanComm_SendCurrentData(&g_fdcan, ch, comm_msg.current_ma[ch]);
                }
                break;

            default:
                break;
            }
        }

        /* ── Check for fault events (higher priority within this task) ── */
        while (osMessageQueueGet(faultEventQueueHandle, &fault_evt, NULL, 0) == osOK) {
            /* Send fault via UART immediately */
            osMutexAcquire(uartTxMutexHandle, osWaitForever);
            UartProtocol_SendFaultData(&g_uart_proto,
                fault_evt.channel, fault_evt.fault);
            osMutexRelease(uartTxMutexHandle);

            /* Send fault via FDCAN */
            FdcanComm_SendFaultEvent(&g_fdcan, &fault_evt);
        }

        /* Heartbeat LED toggle */
        static uint32_t last_heartbeat = 0;
        uint32_t now = osKernelGetTickCount();
        if ((now - last_heartbeat) >= HEARTBEAT_PERIOD_MS) {
            last_heartbeat = now;
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        }
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  HAL Callbacks (ISR → FreeRTOS signaling)
 * ══════════════════════════════════════════════════════════════════════════ */

/**
 * @brief UART RX Complete Callback
 * Called when 1 byte is received via interrupt.
 * Processes the byte and signals the UartCmdTask when a full line is ready.
 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        uint8_t byte = g_uart_proto.rx_buf[0];

        if (UartProtocol_ProcessByte(&g_uart_proto, byte)) {
            /* Complete command line received → signal UartCmdTask */
            osSemaphoreRelease(uartRxSemHandle);
        }

        /* Re-enable UART RX interrupt for next byte */
        HAL_UART_Receive_IT(&huart1, g_uart_proto.rx_buf, 1);
    }
}

/**
 * @brief ADC Conversion Complete Callback (DMA)
 * Internal ADC has finished scanning all 4 current-sense channels.
 */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    if (hadc->Instance == ADC1) {
        /* DMA buffer is already updated (g_adc_dma_buf).
         * FaultDetectTask reads it directly. No copy needed in circular mode. */
    }
}

/**
 * @brief FDCAN RX FIFO0 Callback (for future bidirectional CAN communication)
 */
void HAL_FDCAN_RxFifo0Callback(FDCAN_HandleTypeDef *hfdcan, uint32_t RxFifo0ITs)
{
    if (hfdcan->Instance == FDCAN1) {
        if ((RxFifo0ITs & FDCAN_IT_RX_FIFO0_NEW_MESSAGE) != 0) {
            FDCAN_RxHeaderTypeDef rx_header;
            uint8_t rx_data[8];
            HAL_FDCAN_GetRxMessage(hfdcan, FDCAN_RX_FIFO0, &rx_header, rx_data);
            /* Future: parse CAN commands from external controller */
        }
    }
}

/* ══════════════════════════════════════════════════════════════════════════
 *  FreeRTOS Hook Functions
 * ══════════════════════════════════════════════════════════════════════════ */

/**
 * @brief Malloc Failed Hook - called when pvPortMalloc() fails
 */
void vApplicationMallocFailedHook(void)
{
    /* Blink fault LED rapidly to indicate memory issue */
    for (;;) {
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
        HAL_Delay(100);
    }
}

/**
 * @brief Stack Overflow Hook - called when stack overflow is detected
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    /* Blink both LEDs to indicate stack overflow */
    for (;;) {
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        HAL_Delay(200);
    }
}
