/**
 * Example: automatic ADC calibration on STM32L552 boot.
 *
 * STM32CubeIDE SPI configuration required:
 *
 *   SPI1 (for MCP3465R):
 *     Mode:          Full-Duplex Master
 *     Data Size:     8-bit
 *     CPOL:          Low  (0)
 *     CPHA:          1 Edge (0)  → SPI Mode 0
 *     Baud rate:     ≤ 10 MHz (MCP3465R max 20 MHz)
 *     NSS:           Software (managed by GPIO)
 *     Assigned pins: SCK=PA5, MISO=PA6, MOSI=PA7
 *
 *   SPI2 (for DAC80501):
 *     Mode:          Full-Duplex Master (TX-only acceptable)
 *     Data Size:     8-bit
 *     CPOL:          Low  (0)
 *     CPHA:          2 Edge (1)  → SPI Mode 1
 *     Baud rate:     ≤ 50 MHz (DAC80501 max 50 MHz)
 *     NSS:           Software
 *     Assigned pins: SCK=PB13, MOSI=PB15
 *
 *   GPIO outputs (no pull, push-pull, high speed):
 *     PA4  → MCP3465R /CS
 *     PA8  → DAC80501 /CS
 *
 * Wiring:
 *   DAC80501 VOUT → MCP3465R CH0 (pin 14)
 *   MCP3465R VREF → stable 5.0V reference
 *   MCP3465R AGND → system GND
 */

#include "main.h"          /* generated by STM32CubeIDE */
#include "mcp3465r.h"
#include "dac80501.h"
#include "calibration.h"
#include <stdio.h>         /* printf via SWO or UART retarget */

/* Extern handles generated by STM32CubeIDE MX */
extern SPI_HandleTypeDef hspi1;
extern SPI_HandleTypeDef hspi2;

/* ── Entry point ────────────────────────────────────────────────────────── */

void app_run(void)
{
    HAL_StatusTypeDef st;

    /* --- Initialise peripherals ----------------------------------------- */
    st = MCP3465R_Init();
    if (st != HAL_OK) {
        printf("[CAL] MCP3465R init failed (%d)\r\n", st);
        Error_Handler();
    }

    st = DAC80501_Init();
    if (st != HAL_OK) {
        printf("[CAL] DAC80501 init failed (%d)\r\n", st);
        Error_Handler();
    }

    /* --- Run calibration ------------------------------------------------- */
    printf("[CAL] Starting two-point calibration...\r\n");
    printf("[CAL]   Low  point : %.3f V\r\n", (double)CAL_V_LOW);
    printf("[CAL]   High point : %.3f V\r\n", (double)CAL_V_HIGH);
    printf("[CAL]   VREF (ADC) : %.3f V\r\n", (double)CAL_VREF_ADC);

    CalibrationResult_t cal = {0};
    st = RunCalibration(&cal);
    if (st != HAL_OK) {
        printf("[CAL] RunCalibration failed (%d)\r\n", st);
        Error_Handler();
    }

    /* --- Print results --------------------------------------------------- */
    printf("[CAL] ── Results ───────────────────────────────\r\n");
    printf("[CAL]   OFFSETCAL  : 0x%06lX  (%ld)\r\n",
           (unsigned long)(cal.offsetcal & 0xFFFFFFUL),
           (long)cal.offsetcal);
    printf("[CAL]   GAINCAL    : 0x%06lX  (×%.6f)\r\n",
           (unsigned long)cal.gaincal,
           (double)cal.gaincal / (double)MCP3465R_GAINCAL_UNITY);
    printf("[CAL] ── Verification ──────────────────────────\r\n");
    printf("[CAL]   @ %.3f V  →  measured %.4f V  (err %+.2f mV)\r\n",
           (double)CAL_V_LOW,
           (double)cal.verify_low_v,
           (double)cal.error_low_mv);
    printf("[CAL]   @ %.3f V  →  measured %.4f V  (err %+.2f mV)\r\n",
           (double)CAL_V_HIGH,
           (double)cal.verify_high_v,
           (double)cal.error_high_mv);
    printf("[CAL]   Result     : %s\r\n", cal.pass ? "PASS" : "FAIL");

    if (!cal.pass) {
        printf("[CAL] WARNING: residual error exceeds %.1f mV threshold\r\n",
               (double)CAL_PASS_THRESHOLD_MV);
    }

    /* --- Normal operation: read ADC continuously -------------------------- */
    printf("[CAL] Entering normal ADC read loop...\r\n");
    for (;;) {
        int32_t code;
        st = MCP3465R_ReadRaw24(&code);
        if (st == HAL_OK) {
            float v = MCP3465R_Code24ToVoltage(code, CAL_VREF_ADC);
            printf("[ADC] code=%8ld  voltage=%.4f V\r\n", (long)code, (double)v);
        }
        HAL_Delay(100);
    }
}

/* Call app_run() from main() after MX_SPIx_Init() calls, e.g.:
 *
 *   int main(void) {
 *       HAL_Init();
 *       SystemClock_Config();
 *       MX_GPIO_Init();
 *       MX_SPI1_Init();
 *       MX_SPI2_Init();
 *       app_run();   // does not return
 *   }
 */
